language: ruby
rvm:
  - 2.1.1

gemfile:
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile

    
notifications:
  irc: "irc.freenode.org#projecthydra"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
