language: ruby
cache: bundler
sudo: false
rvm: 2.4.1
matrix:
  include:
    - rvm: 2.3.4
      env: "RAILS_VERSION=4.2.8"
    - env: "RAILS_VERSION=5.1.1"
global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
before_script:
  - jdk_switcher use oraclejdk8
