language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.0

notifications:
  irc: "irc.freenode.org#projecthydra"

env:
  - "RAILS_VERSION=4.2.6"

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
  - jdk_switcher use oraclejdk8
