development:
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
test:
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora-test
production:
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8080/fedora
    
