# The default namespace maps to the default namespace for generating rels_ext from solr
:default_namespace: info:fedora/fedora-system:def/relations-external#

# namespace mappings--- 
# you can add specific mappings for your institution by providing the following:
#   namespace_uri:
#     :relationship_symbol: relationship_identifier
# 
# For example, if you have the following element in your rels_ext:
#  
#  <oai:itemID>oai:example.edu:changeme:500</oai:itemID>
# 
# With the last two lines of this file uncommented, the relationships hash of your object will include:
#   :oai_item_id => ["info:fedora/oai:example.edu:changeme:500"]
#
:predicate_mapping:
  info:fedora/fedora-system:def/relations-external#: 
    :conforms_to: conformsTo
    :has_annotation: hasAnnotation
    :has_collection_member: hasCollectionMember
    :has_constituent: hasConstituent
    :has_dependent: hasDependent
    :has_derivation: hasDerivation
    :has_description: hasDescription
    :has_equivalent: hasEquivalent
    :has_metadata: hasMetadata
    :has_member: hasMember
    :has_model: hasModel
    :has_part: hasPart
    :has_subset: hasSubset
    :is_annotation_of: isAnnotationOf
    :is_constituent_of: isConstituentOf
    :is_dependent_of: isDependentOf
    :is_derivation_of: isDerivationOf
    :is_description_of: isDescriptionOf
    :is_member_of: isMemberOf
    :is_member_of_collection: isMemberOfCollection
    :is_metadata_for: isMetadataFor
    :is_part_of: isPartOf
    :is_subset_of: isSubsetOf
    :is_topic_of: isTopicOf
  info:fedora/fedora-system:def/model#:
    :has_model: hasModel
    :has_service: hasService
  http://www.openarchives.org/OAI/2.0/: 
    :oai_item_id: itemID
