id: id
default: searchable
searchable:
  date: _date
  string: _field
  text: _field
  symbol: _field
  integer: _field
  long: _field
  boolean: _field
  float: _field
  double: _field
displayable: _display
facetable: _facet
sortable: _sort
unstemmed_searchable: _unstem_search